# Inherit from base config
defaults:
  - base_config

# Override specific settings for this Google Fonts baseline run
run_name: "sdxl_vae_baseline_fonts_256_15e"
project_name: "vae-dyn" # Ensure this matches your wandb project

# threshold to consider neuron/weight as "dead" (for potential analysis/classification)
threshold: 1e-5

# Data settings for Google Fonts
data:
  dataset_name: "rcugarte/genfonts_data" # Google Fonts dataset on Hub
  # dataset_config_name: null    # This dataset likely doesn't need a specific config name
  image_column: "image"          # Default image column name
  resolution: 256                # Keep 256 resolution for consistency
  max_samples: null              # Use the full training split
  batch_size: 8                  # Adjust based on VRAM
  num_workers: 4                 # Increase workers if I/O is bottleneck

# Training settings - keep similar to imagenette run for comparison
training:
  num_train_epochs: 15           # Train for 15 epochs
  learning_rate: 2e-5            # Keep LR similar
  gradient_accumulation_steps: 1 # Adjust with batch_size if needed
  mixed_precision: "no"        # Use fp16 for speed/memory (ensure GPU compatibility)
  kl_weight: 1e-6
  max_grad_norm: 1.0
  lr_warmup_steps: 250

# Logging and Saving
logging:
  log_interval: 100              # Log less frequently for longer runs
  report_to: "wandb"
  entity: "vae-dyn"              # Your W&B entity
saving:
  save_interval: 1000            # Save less frequently
  checkpoint_dir_prefix: "chkpt"

# Ensure tracking/intervention are disabled for baseline
tracking:
  enabled: false
classification:
  enabled: false
intervention:
  enabled: false

